= Hibernate Tools 4.29.1.Final What's New
:page-layout: whatsnew
:page-component_id: hibernate
:page-component_version: 4.29.1.Final
:page-product_id: jbt_core
:page-product_version: 4.29.1.Final

== Older hibernate runtime disabled by default

The old 5.4, 5.5, 6.0, 6.1, 6.2, 6.3 and 6.4 Hibernate Runtiles are now disabled by default.

== Hibernate Runtime Provider Updates

Multiple additions and updates have been performed on the available Hibernate runtime providers.

=== New Runtime Providers

A new Hibernate 6.5 runtime provider incorporates Hibernate Core version 6.5.2.Final, Hibernate Ant version 6.5.2.Final and Hibernate Tools version 6.5.2.Final.

A new Hibernate 6.6 runtime provider incorporates Hibernate Core version 6.6.0.Alpha1, Hibernate Ant version 6.6.0.Alpha1 and Hibernate Tools version 6.6.0.Alpha1.

=== Runtime Provider Updates

The Hibernate 6.4 runtime provider now incorporates Hibernate Core version 6.4.8.Final, Hibernate Ant version 6.4.8.Final and Hibernate Tools version 6.4.8.Final.

The Hibernate 6.3 runtime provider now incorporates Hibernate Core version 6.3.2.Final, Hibernate Ant version 6.3.2.Final and Hibernate Tools version 6.3.2.Final.

The Hibernate 6.2 runtime provider now incorporates Hibernate Core version 6.2.25.Final, Hibernate Ant version 6.2.25.Final and Hibernate Tools version 6.2.25.Final.

The Hibernate 5.3 runtime provider now incorporates Hibernate Core version 5.3.36.Final and Hibernate Tools version 5.3.36.Final.

