#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cd $OPENSHIFT_REPO_DIR

echo "* Setting up environment"
echo "  * Installing awestruct"
gem install bundler
bundle install

echo "* Generating site"


bundle exec awestruct -P staging -g

echo "* Publishing site"
mkdir -p ${OPENSHIFT_REPO_DIR}php
rm -rf ${OPENSHIFT_REPO_DIR}php/*
mv _site/* ${OPENSHIFT_REPO_DIR}php

echo "* Done"