= Freemarker What's New in 4.4.1.AM2
:page-layout: whatsnew
:page-component_id: freemarker
:page-component_version: 4.4.1.AM2
:page-product_id: jbt_core
:page-product_version: 4.4.1.AM2

== Freemarker 2.3.25

Freemarker library included in the Freemarker IDE was updated to latest available version 2.3.25.

related_jira::JBIDE-22700[]

== flth / fltx file extensions added

The new flth and fltx extensions have been added and associated with Freemarker IDE. `flth` stands for HTML content whereas `fltx` stands for XML content.

related_jira::JBIDE-22636[]

== Overhaul of the plugin template parser

The parser that FreeMarker IDE uses to extract IDE-centric information
(needed for syntax highlighting, related tag highlighting,
auto-completion, outline view, etc.) was overhauled. Several bugs were
fixed, and support for the newer template language features were
added. Also, the syntax highlighting is now more detailed inside
expressions.

related_jira::JBIDE-20180,JBIDE-22574,JBIDE-21819[]

== Related tag background highlighting fixed

Fixed the issue when the (by default) yellow highlighting of the
related FTL tags shift away from under the tag as you type.

related_jira::JBIDE-22656[]

== Showing whitespace, block selection mode

The standard "Show whitespace characters" and "Toggle block selection
mode" icons are now available when editing a template.

related_jira::JBIDE-22751[]
