= Community Acceptance Testing (CAT)
:page-layout: project
:page-status: red

== JBoss Tools Community Acceptance Testing (CAT)

Welcome to JBoss Tools Community Acceptance Testing (JBoss Tools CAT)!

JBoss Tools CAT is an effort to get better and early feedback that the
features in JBoss Tools are working well and getting confirmation from
JBoss Tools and Developer Studio community that the quality is ready
for the final release.

== Get started

To particpate please follow these steps:

* Register for community membership here: http://bit.ly/jbosstoolscatsignup[registration form]
* Subscribe to the community mailing list here: https://lists.jboss.org/mailman/listinfo/jbosstools-cat[email subscription form]
* Download the latest JBoss Tools bits - as of today - you should download: http://tools.jboss.org/downloads/jbosstools/luna/4.2.0.Beta2.html
* And, then start testing!

== Organization

The idea is to get as much feedback on our Alpha, Beta and CR builds
as possible.  We are looking for feedback on usability, quality and
performance for new features, and especially also for reports on any 
regression for existing features that you already are using.

== CAT Member responsibilities

As a member of the JBoss Tools CAT team you are asked to give feedback
on the two functional areas you chose to focus on. It is fully
acceptable to only use the Beta and CR builds, but it is highly
recommended and appreciated if you use and tested the nightly
development builds too.

You can communicate to the JBoss Tools team and other CAT members via
the CAT community forum, the mailing list or jira.

We may request additional input via surveys or online IRC meetings when JBoss Tools CAT 
is active and at the end of a release we will send a survey where you can express your opinion
on wether the new features are ready for release and the features you depend on have not regressed.

=== Resources

.JBoss Tools CAT Resources
|===
|Name | Description | Link |

|Mailing list (mailto:jbosstools-cat@lists.jboss.org) 
| Archived mailing list for JBoss Tools CAT. Synchronized with the community forum 
| https://lists.jboss.org/mailman/listinfo/jbosstools-cat[Signup] http://lists.jboss.org/pipermail/jbosstools-dev/[Archive]

| Forum
| Online forum on jboss.org 
| link

| Chat
| irc chat room on #freenode
| irc://irc.freenode.org/jbosstools-cat 

| Dashboard
| jira dashboard for issues found by JBoss Tools CAT team
| https://jira...
|===

