= Community Acceptance Testing (CAT)
:page-layout: project
:page-status: red

== JBoss Tools Community Acceptance Testing (CAT)

Welcome to JBoss Tools Community Acceptance Testing (JBoss Tools CAT)!

JBoss Tools CAT is an effort to get better and early feedback that the
features in JBoss Tools are working well and getting confirmation from
JBoss Tools and Developer Studio community that the quality is ready
for the final release.

The goal of the JBoss Tools CAT is to get as much feedback on our Alpha, Beta and pre-GA 
builds as possible.  We are looking for feedback on usability, quality and
performance for new features, and especially also for reports on any 
regression for existing features that you already are using.

== Get started

To particpate please follow these steps:

* Register for community membership here: http://bit.ly/jbosstoolscatsignup[registration form]
* Subscribe to the JBoss Tools CAT mailing list here: https://lists.jboss.org/mailman/listinfo/jbosstools-cat[email subscription form]
* Download the latest JBoss Tools bits - as of today - you should download: http://tools.jboss.org/downloads/jbosstools/luna/4.2.0.Beta2.html
* Request a JBoss JIRA account (to be used to log bugs and feature requests): https://issues.jboss.org[JBoss JIRA]
* And, then start testing!

== CAT Member responsibilities

What types of tests should you perform? 

As a member of the JBoss Tools CAT team you are asked to give feedback
on the two functional areas you choose to focus on. It is fully
acceptable to only use the Beta and CR builds, but it is highly
recommended and appreciated if you use and test the nightly
development builds too. 

So, select the features in JBoss Tools that you are most interested in, and start testing!

You can communicate to the JBoss Tools team and other CAT members via
the CAT community forum, irc, the mailing list or jira.

We may request additional input via surveys or online IRC meetings when JBoss Tools CAT 
is active and at the end of a release we will send a survey where you can express your opinion
on whether the new features are ready for release and the features you depend on have not regressed.

== What Happens to Bugs and Feature Requests?

The JBoss Tools CAT team managers will review and respond to all new bugs and feature requests.

== Resources - How Can JBoss Tools CAT Members get Help with Questions?


.JBoss Tools CAT Resources
|===
|Name | Description | Link 

|Mailing list (mailto:jbosstools-cat@lists.jboss.org) 
| Archived mailing list for JBoss Tools CAT. Synchronized with the community forum 
| https://lists.jboss.org/mailman/listinfo/jbosstools-cat[Signup] http://lists.jboss.org/pipermail/jbosstools-dev/[Archive]

| Forum
| Online forum on jboss.org 
| link (TBD)

| Chat
| irc chat room on #freenode
| irc://irc.freenode.org/jbosstools-cat 

| Dashboard
| jira dashboard for issues found by JBoss Tools CAT team
| link (TBD)
|===

