eclipse:
  luna:
    url_path_fragment: luna
    short_name: Luna
    full_name: Eclipse Luna 4.4
    download_url: http://www.eclipse.org/downloads/index-developer.php
    requirements: Java 7
  kepler:
    url_path_fragment: kepler
    short_name: Kepler
    full_name: Eclipse Kepler 4.3
    download_url: http://www.eclipse.org/downloads/packages/release/kepler/sr1
    requirements: Java 6 or Java 7
  juno:
    url_path_fragment: juno
    short_name: Juno
    full_name: Eclipse Juno 4.2.2
    download_url: http://www.eclipse.org/downloads/packages/release/juno/sr2
    requirements: Java 6
  indigo:
    url_path_fragment: indigo
    short_name: Indigo
    full_name: Eclipse Indigo 3.7
    requirements: Java 6
  ganymede:
    url_path_fragment: ganymede
    short_name: Ganymede
    full_name: Eclipse Ganymede 3.6
    requirements: Java 5

# Product types
devstudio: 
  name: JBoss Developer Studio
  url_path_fragment: devstudio
  streams:
    luna:
      8.0.0.Alpha1:
        active: true
        release_date: 
        marketplace_install_url: 
    kepler:
      7.1.0.GA:
        active: true
        release_date: 2013-12-16
        documentation_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/
        release_notes_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/7.1/html-single/Release_Notes_7.1.0/index.html
        blog_announcement_url: http://bit.ly/jbt-411
        marketplace_url: http://marketplace.eclipse.org/node/827807
        marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=827807
        download_url: https://www.jboss.org/products/devstudio
        zips:
          - name: Update site (including sources) bundle of JBoss Developer Studio
            download_size: 719MB
            url: https://devstudio.jboss.com/updates/7.0.0/jbdevstudio-updatesite-7.1.0.GA-v20131208-0703-B592.zip
            md5_url: https://devstudio.jboss.com/updates/7.0.0/jbdevstudio-updatesite-7.1.0.GA-v20131208-0703-B592.zip.MD5
      7.0.1.GA:
        active: false
        release_date: 2013-09-23
        documentation_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/
        release_notes_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/7.0/html-single/Release_Notes_7.0.1/index.html
        blog_announcement_url: https://community.jboss.org/community/tools/blog/2013/07/23/jboss-tools-41-and-developer-studio-7-go-ga
        download_url: https://devstudio.jboss.com/earlyaccess/7.0.0.GA.html
        zips:
          - name: Update site (including sources) bundle of JBoss Developer Studio
            download_size: 696MB
            url: https://devstudio.jboss.com/updates/7.0.0/jbdevstudio-updatesite-7.0.1.GA-v20130930-2238-B7.zip
            md5_url: https://devstudio.jboss.com/updates/7.0.0/jbdevstudio-updatesite-7.0.1.GA-v20130930-2238-B7.zip.MD5
    juno:
      6.0.1.GA:
        active: false
        release_date: 2012-11-01
        documentation_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/
        release_notes_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/6.0/html-single/6.0.1_Release_Notes/index.html
        marketplace_url: http://marketplace.eclipse.org/node/503834
        marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=503834
        download_url: https://devstudio.jboss.com/download/6.x.html
        zips:
          - name: Update site (including sources) bundle of JBoss Developer Studio
            download_size: 441MB
            url: https://devstudio.jboss.com/updates/6.0.0/jbdevstudio-updatesite-6.0.1.GA-v20130327-2052-B361.zip
            md5_url: https://devstudio.jboss.com/updates/6.0.0/jbdevstudio-updatesite-6.0.1.GA-v20130327-2052-B361.zip.MD5
    indigo:
      5.0.2.GA:
        active: false
        release_date: 2012-06-21
        documentation_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/
        release_notes_url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Developer_Studio/5.0/html-single/5.0.2_Release_Notes/index.html
        marketplace_url: http://marketplace.eclipse.org/node/121986
        marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=121986
        download_url: https://devstudio.jboss.com/download/5.x.html
        zips:
          - name: Update site (including sources) bundle of JBoss Developer Studio
            download_size: 373MB
            url: https://devstudio.jboss.com/updates/5.0.0/jbdevstudio-updatesite-5.0.2.v20130119-0035-H249-GA.zip
            md5_url: https://devstudio.jboss.com/updates/5.0.0/jbdevstudio-updatesite-5.0.2.v20130119-0035-H249-GA.zip.MD5

jbt_core: 
  name: JBoss Tools
  url_path_fragment: jbosstools
  streams:
    luna:
      4.2.0.Alpha1:
        release_date: 2013-12-19
        active: true
        documentation_url: http://docs.jboss.org/tools/
        update_site_url: http://download.jboss.org/jbosstools/updates/development/luna/
        download_url: http://www.jboss.org/tools/download/dev/4_2_x
        zips:
          - name: Update site (including sources) bundle of all JBoss <b style="color:green">Core</b> Tools
            download_size: 438MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/jbosstools-Update-4.2.0.Alpha1_2013-11-24_01-06-56-B575.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/jbosstools-Update-4.2.0.Alpha1_2013-11-24_01-06-56-B575.zip.MD5
          - name: Sources zip of all JBoss <b style="color:green">Core</b> Tools
            download_size: 98MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/jbosstools-Sources-4.2.0.Alpha1_2013-11-24_01-06-56-B575.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/jbosstools-Sources-4.2.0.Alpha1_2013-11-24_01-06-56-B575.zip.MD5
          - name: Update site (including sources) bundle of all <b style="color:green">Hibernate Tools</b>
            download_size: 81MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/hibernatetools-Update-4.2.0.Alpha1_2013-12-11_01-09-15-B32.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/hibernatetools-Update-4.2.0.Alpha1_2013-12-11_01-09-15-B32.zip.MD5
          - name: Release Notes
            download_size: 59kB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.2.0.x/zz_Release_Notes_4.2.0.Alpha1.readme.html
      4.2.0.Nightly: 
        active: true  
        update_site_url: http://download.jboss.org/jbosstools/updates/nightly/core/master/
        download_url: http://download.jboss.org/jbosstools/builds/nightly/core/master/latestBuild.html
    kepler:
      4.1.1.Final:
        active: true
        release_date: 2013-12-16
        documentation_url: http://docs.jboss.org/tools/4.1.x.Final/
        whatsnew_url: http://docs.jboss.org/tools/whatsnew/
        blog_announcement_url: http://bit.ly/jbt-411
        marketplace_url: http://marketplace.eclipse.org/node/876523
        marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=876523
        update_site_url: http://download.jboss.org/jbosstools/updates/stable/kepler/
        zips:
          - name: Update site (including sources) bundle of all JBoss <b style="color:green">Core</b> Tools
            download_size: 438MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Update-4.1.1.Final_2013-12-08_01-06-33-B605.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Update-4.1.1.Final_2013-12-08_01-06-33-B605.zip.MD5
          - name: Sources zip of all JBoss <b style="color:green">Core</b> Tools
            download_size: 98MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Sources-4.1.1.Final_2013-12-08_01-06-33-B605.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Sources-4.1.1.Final_2013-12-08_01-06-33-B605.zip.MD5
          - name: Update site (including sources) bundle of all <b style="color:green">Hibernate Tools</b>
            download_size: 82MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/hibernatetools-Update-4.1.1.Final_2013-12-08_01-06-33-B605.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/hibernatetools-Update-4.1.1.Final_2013-12-08_01-06-33-B605.zip.MD5
          - name: Release Notes
            download_size: 7.5kB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/zz_Release_Notes_4.1.1.Final.readme.html
      4.1.0.Final:
        active: false
        release_date: 2013-07-23
        documentation_url: http://docs.jboss.org/tools/4.1.0.Final/
        whatsnew_url: http://docs.jboss.org/tools/whatsnew/
        blog_announcement_url: https://community.jboss.org/community/tools/blog/2013/07/23/jboss-tools-41-and-developer-studio-7-go-ga
        # comment out marketplace and update site because these will now link to 4.1.1, not 4.1.0
        #marketplace_url: http://marketplace.eclipse.org/node/876523
        #marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=876523
        #update_site_url: http://download.jboss.org/jbosstools/updates/stable/kepler/
        zips:
          - name: Update site (including sources) bundle of all JBoss <b style="color:green">Core</b> Tools 4.1.0.1
            download_size: 429MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Update-4.1.0.1.Final_2013-09-23_20-11-14-B5.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Update-4.1.0.1.Final_2013-09-23_20-11-14-B5.zip.MD5
          - name: Sources zip of all JBoss <b style="color:green">Core</b> Tools 4.1.0.1
            download_size: 1.1MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Sources-4.1.0.1.Final_2013-09-23_20-11-14-B5.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Sources-4.1.0.1.Final_2013-09-23_20-11-14-B5.zip.MD5
          - name: Sources zip of all JBoss <b style="color:green">Core</b> Tools 4.1.0
            download_size: 98MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Sources-4.1.0.Final_2013-07-19_19-47-52-B380.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/jbosstools-Sources-4.1.0.Final_2013-07-19_19-47-52-B380.zip.MD5
          - name: Update site (including sources) bundle of all <b style="color:green">Hibernate Tools</b> 4.1.0
            download_size: 82MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/hibernatetools-Update-4.1.0.Final_2013-07-19_19-47-52-B380.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/hibernatetools-Update-4.1.0.Final_2013-07-19_19-47-52-B380.zip.MD5
          - name: Release Notes 4.1.0.1
            download_size: 5.7kB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/zz_Release_Notes_4.1.0.1.Final.readme.html
          - name: Release Notes 4.1.0
            download_size: 5.7kB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.1.x/zz_Release_Notes_4.1.0.Final.readme.html
      4.1.1.Nightly:   
        documentation_url: http://docs.jboss.org/tools/
        update_site_url: http://download.jboss.org/jbosstools/updates/nightly/core/4.1.kepler/
        download_url: http://download.jboss.org/jbosstools/builds/nightly/core/4.1.kepler/

    juno:
      4.0.1.Final:
        active: false
        release_date: 2013-04-03
        marketplace_url: http://marketplace.eclipse.org/node/420896
        marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=420896
        update_site_url: http://download.jboss.org/jbosstools/updates/stable/juno/
        zips:
          - name: Update site (including sources) bundle of all JBoss <b style="color:green">Core</b> Tools
            download_size: 203MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/jbosstools-4.0.1.Final.aggregate-Update-2013-03-27_16-17-05-B340.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/jbosstools-4.0.1.Final.aggregate-Update-2013-03-27_16-17-05-B340.zip.MD5
          - name: Sources zip of all JBoss <b style="color:green">Core</b> Tools
            download_size: 100MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/jbosstools-4.0.1.Final.aggregate-Sources-2013-03-27_16-17-05-B340.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/jbosstools-4.0.1.Final.aggregate-Sources-2013-03-27_16-17-05-B340.zip.MD5
          - name: Update site (including sources) bundle of all <b style="color:green"><b style="color:green">Hibernate Tools</b></b>
            download_size: 43MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/jbosstools-4.0.1.Final.component--hibernatetools-Update-2013-03-27_16-17-05-B340.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/jbosstools-4.0.1.Final.component--hibernatetools-Update-2013-03-27_16-17-05-B340.zip.MD5
          - name: Release Notes
            download_size: 8.6kB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools4.0.x/zz_Release_Notes_4.0.1.Final.readme.html

    indigo:
      3.3.2.Final:
        active: false
        release_date: 2013-01-25
        marketplace_url: http://marketplace.eclipse.org/node/121986
        marketplace_install_url: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=121986
        update_site_url: http://download.jboss.org/jbosstools/updates/stable/indigo/
        zips:
          - name: Update site (including sources) bundle of all JBoss <b style="color:green">Core</b> Tools
            download_size: 237MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/jbosstools-3.3.2.Final.aggregate-Update-2013-01-18_18-03-25-H229.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/jbosstools-3.3.2.Final.aggregate-Update-2013-01-18_18-03-25-H229.zip.MD5
          - name: Sources zip of all JBoss <b style="color:green">Core</b> Tools
            download_size: 107MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/jbosstools-3.3.2.Final.aggregate-Sources-2013-01-18_18-03-25-H229.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/jbosstools-3.3.2.Final.aggregate-Sources-2013-01-18_18-03-25-H229.zip.MD5
          - name: Update site (including sources) bundle of all <b style="color:green">Hibernate Tools</b>
            download_size: 70MB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/jbosstools-3.3.2.Final.component--hibernatetools-Update-2013-01-18_18-03-25-H229.zip
            md5_url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/jbosstools-3.3.2.Final.component--hibernatetools-Update-2013-01-18_18-03-25-H229.zip.MD5
          - name: Release Notes
            download_size: 12kB
            url: http://sourceforge.net/projects/jboss/files/JBossTools/JBossTools3.3.x/zz_Release_Notes_3.3.2.Final.readme.html
