title: JBoss Tools

# Project id name
project: tools

# Project name
project_name: JBoss Tools

encoding: UTF-8

textile:
  :no_span_caps: true

asciidoctor:
  :safe: safe
  :compact: true
  :eruby: erubis
  :attributes:
    imagesdir: ./@
    icons: font
    experimental: true
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    linkattrs: ''
  
# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: false
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-misc.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js
    - /javascripts/_jbossorg-tabzilla.js
    
# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 864000 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/example/

  
profiles:
  development:
    showwip: false
    base_url: http://localhost:4242
    jborg_fonts_url: /cache/static.jboss.org/theme/fonts
    jborg_images_url: /cache/static.jboss.org/theme/images
    jborg_js_url: /cache/static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/tools
    bootstrap_css_url: /stylesheets/bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    disqus: jbosstools-dev
    
  staging:
    showwip: true
    base_url: http://tools-stg.jboss.org/master
    minified: .min
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/tools
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.4/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.4/bootstrap-community
    disqus: jbosstools-preview
    deploy:
      host: github_pages
      repository: origin
      branch: gh-pages
    google_analytics: UA-46704212-1
    
  new_noteworthy:
    showwip: true
    base_url: http://tools-stg.jboss.org/new_noteworthy
    minified: .min
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/tools
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.4/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.4/bootstrap-community
    disqus: jbosstools-preview
    deploy:
      host: github_pages
      repository: origin
      branch: gh-pages
    google_analytics: UA-46704212-1
  
  production:
    showwip: false
    base_url: http://tools.jboss.org
    minified: .min
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/tools
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.4/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.4/bootstrap-community
    google_analytics: UA-17645367-6
    disqus: jbosstools
    
      
  


    
