= Google API OAuth with CordovaSim 
:page-layout: blog
:page-author: ibuziuk
:page-tags: [phonegap, oauth, cordova, inappbrowser, cordovasim, aerogear, jbosscentral]

In this article I'm happy to introduce you the http://oauth.net/[OAuth] authorization via Phonegap's https://github.com/apache/cordova-plugin-inappbrowser[inAppBrowser] plugin with https://github.com/jbosstools/jbosstools-aerogear/tree/master/cordovasim[CordovaSim]. 

I was inspired to write this blog after reading a great article about http://phonegap-tips.com/articles/google-api-oauth-with-phonegaps-inappbrowser.html[Google API OAuth with PhoneGap's InAppBrowser] by Michael Dellanoce. I also want to spill the beans about new CordovaSim's features like: *JavaFx web engine*, *hybrid app debugging* and *eclipse console logging* that will be availale in Beta3 but you can try now from the nightly link:../downloads/jbosstools/luna/4.2.0.Nightly.html[4.2.x updatesite].

== Overview
http://oauth.net/[OAuth] is an open standard for authorization. It specifies a process for resource owners to authorize third-party access to their server resources without sharing their credentials. Designed specifically to work with Hypertext Transfer Protocol (HTTP), OAuth essentially allows access tokens to be issued to third-party clients by an authorization server, with the approval of the resource owner, or end-user. PhoneGap Developers use https://github.com/apache/cordova-plugin-inappbrowser/blob/master/doc/index.md[inAppBrowser's API] to show the OAuth consent page.

== Demo 
https://github.com/jbosstools/jbosstools-aerogear/tree/master/cordovasim[CordovaSim] supports inAppBrowser plugin and handles OAuth authorization. Here is a short https://vimeo.com/98135061[video] with OAuth demo and brand-new CordovaSim's features (https://github.com/mdellanoce/google-api-oauth-phonegap/tree/master[source code] is also taken from the Michael Dellanoce's article):

video::98135061[vimeo, width=640, height=400]

== How to give it a go?
The sample should work with `JBoss Tools 4.2.0 Beta3` release and the following. 
[square]
* Clone the demo https://github.com/mdellanoce/google-api-oauth-phonegap/tree/master[project]
* File -> Import -> Import Cordova Project
* Right click on the project -> Properties -> Hybrid Mobile Engine -> Download -> 3.4.0 (select as default engine)
* Create a https://console.developers.google.com/[Google Developers Console] project
* Copy and paste *Client ID* and *Client secret* to index.js (lines 80-81) of the hybrid project
* Right click on the project -> Run As.. -> Run with CordovaSim

A few things to notice here. First that the Hybrid Mobile Tools imports the project into eclipse and configure the proper plugins without there being
any eclipse specfic setup in the project. This works because the project is following the conventions from Cordova CLI generated project and the import wizard groks this.

Finally when using Java 8 you can connect with chrome debugger to the CordovaSimulator (Right click -> Debug on browser) allowing you to step through the code, introspect
variables and so forth. 
   
== Conclusion
We are trying our best to make CordovaSim as good as possible. Users feedback is what we are seeking for now. We are looking forward to hearing your comments / remarks! +
Have fun!

Ilya Buziuk +
https://twitter.com/ilyabuziuk[@ilyabuziuk]