= New HTML Preview is taking shape!
:page-layout: blog
:page-author: ibuziuk
:page-tags: [jbosstools, jbds, html, vpe, WYSIWYG, XULRunner]

In this article I'm happy to introduce you a brand new HTML Preview without XULRunner. Basically, HTML Preview could be treated as a possible XULRunner substitution. The point is that when XULRunner is unavailable, HTML Preview will be used in "Visual/Source" and "Preview" tabs of the https://github.com/jbosstools/jbosstools-vpe[VPE]. It will be also available as a separate view and won't be coupled with a paticular editor.

== Overview
HTML Preview has several cool features like:

 -  automatic refresh (enabled by default)
 -  refresh on save
 -  navigation from source to view and vice versa

Here is a short demo video, which covers basic use case :

video::92255691[vimeo, width=640, height=400]

== How can I try it?
HTML Preview is not in production yet. It will be a part of JBoss Tools and Developer Studio Beta2 release for Eclipse Luna. However, you can always get access to the "snapshot" build of JBoss Tools http://download.jboss.org/jbosstools/builds/staging/jbosstools-build-sites.aggregate.site_master/all/repo/[here]. When we push changes, it should be maximum a few hours before  you will be able to test the actual result.

== Conclusion
We are trying our best to make HTML Preview as good as possible. Users' feedback is what we are seeking for now. We are looking forward to hearing your comments / remarks! +
Have fun!

Ilya Buziuk +
https://twitter.com/ilyabuziuk[@ilyabuziuk]