= JBoss Tools 4.9.0.AM3 for Eclipse 2018-09 M2
:page-layout: blog
:page-author: jeffmaury
:page-tags: [release, jbosstools, devstudio, jbosscentral]
:page-date: 2018-09-11

Happy to announce 4.9.0.AM3 (Developer Milestone 3) build for Eclipse 2018-09 M2.

Downloads available at link:/downloads/jbosstools/2018-09/4.9.0.AM3.html[JBoss Tools 4.9.0 AM3].

== What is New?

Full info is at link:/documentation/whatsnew/jbosstools/4.9.0.AM3.html[this page]. Some highlights are below.

=== General

=== Server Tools

==== Wildfly 14 Server Adapter

A server adapter has been added to work with Wildfly 14. It adds support for Java EE 8. 

=== Forge Tools

==== Forge Runtime updated to 3.9.1.Final

The included Forge runtime is now 3.9.1.Final. Read the official announcement https://forge.jboss.org/news/jboss-forge-3.9.1.final-is-here[here].

=== Fuse Tooling

==== Know issues

A regression has been introduced touching all functionalities using Jaxb. It includes:

- Variable content display in debug
- Data Transformation wizard
- Tracing Camel route via Jolokia Connection

It may affect other functionalities. In this case, you will have this kind of error in log:

	java.lang.NullPointerException
		at javax.xml.bind.ContextFinder.handleClassCastException(ContextFinder.java:95)
	
Please note that it has been already fixed on link:http://tools.jboss.org/downloads/jbosstools/2018-09/4.9.x.Nightly.html[nightly build]


Enjoy!

Jeff Maury