= We are hiring
:page-date: 2015-09-16
:page-layout: blog
:page-author: maxandersen
:page-tags: [job, jbosscentral]

The Developer Experience and Tooling group, of which JBoss Tools team is part, 
have a set of job openings available. We are looking to continue
improving the usability for developers around Eclipse and around the Red Hat product line, including JBoss Middleware.

Topics range from Java to JavaScript, application servers to containers, source code tinkering to full blown CI/CD setups.

If you are into making developers life easier and like to be able to get involved in many different technologies and get them to work great together then do apply for one of the current listings.

You can also ping me (manderse@redhat.com) for questions.

The current list of openings are:

* http://jobs.redhat.com/jobs/descriptions/principal-software-engineer-mountain-view-california-job-1-5796888[Principal software engineer]
* http://jobs.redhat.com/jobs/descriptions/senior-software-engineer-brno-jihomoravsky-kraj-czech-republic-job-1-5796893[Senior software engineer]
* http://jobs.redhat.com/jobs/descriptions/senior-software-engineer-brno-jihomoravsky-kraj-czech-republic-job-1-5796887[Senior software engineer]
* http://jobs.redhat.com/jobs/descriptions/senior-software-engineer-mountain-view-california-job-1-5796895[Senior software engineer]

Note: the job postings do list a specific location, but for the right candidate we are happy to consider many locations worldwide (anywhere there is a Red Hat office), as well as working from home.

Have fun! +
Max Rydahl Andersen +
http://twitter.com/maxandersen[@maxandersen]
