= Arquillian What's New in 4.3.0.Alpha1
:page-layout: whatsnew
:page-component_id: arquillian
:page-component_version: 4.3.0.Alpha1
:page-product_id: jbt_core 
:page-product_version: 4.3.0.Alpha1

== Better support for ShrinkWrap API in Generate Deployment

Dependent classes for the same package are added with addClasses(...) instead of using addClass on all individually.

related_jira::JBIDE-18270[]

== 'Export Archive' to Arquillian Cruiser view

An archive can be exported by right-clicking an archive entry in the Arquillia Cruiser view and selecting the Export Archive action.

related_jira::JBIDE-16385[]

== ShrinkWrap Archive file location validation

Arquillian warns that known EE descriptor files are in a wrong location

related_jira::JBIDE-14782[]

== Maven configurator for arquillian

Now, Arquillian includes a Maven configurator that configures arquillian capabilities if a project includes arquillian classes.
The configurator is disabled by default.

related_jira::JBIDE-14427[]
 